### ISSUE TITLE
AnonCreds method registry and issuer key management

### ISSUE THREAD

**Issue by PatStLouis** [openwallet-foundation/credential-format-comparison-sig#66]
[Here is a link to the AnonCreds method registry](https://hyperledger.github.io/anoncreds-methods-registry/#registry).

Should `did:web` & `did:cheqd` be added to the issuer's key management? One of the goal of the anoncreds specification was to remove dependence to indy.

**Comment by cre8** [comment]
In this case we would have new profiles and need to update the current one.
Todos:
- rename the current anoncred profile to anoncreds with did:indy
- add the other profiles like did:cheqd, did:web
- in case of cheqd, we also need to add they as a new key management
