### ISSUE TITLE
Signature format is missing

### ISSUE THREAD

**Issue by alenhorvat** [openwallet-foundation/credential-format-comparison-sig#84]
VCs have a format, but so do signatures.

I cannot find a category for signature formats.

**Comment by cre8** [comment]
You mean like JSON Web Signatures?

When defining the profiles we saw differences in them, just the Format. When we define a profile that is using the VC Data Model, your wallet needs to support all requirements of it like the defined signature formats that can be placed inside a VC Data model. But VC Data Model is not defining the Signature Algorithm (like RSA, ECDSA), it just says "put your public key in a public key format i defined here".

If you have any good example why we should add it, feel free to open the issue again :)

**Comment by alenhorvat** [comment]
Hi.

Nice example are JWS and JAdES (JSON Advanced Electronic digital Signature) and even CAdES (same as JAdES but can secure any digest).

JWS/JAdES/CAdES have the ability so secure any payload: from JSON, JSON-LD, or any other document (e.g., CAdES as input requires only the digest of the protected content; content type/format can be anything).

In this sense JAdES can secure: VCDM v1.1, v2; JWT-VC, JWT, SD-JWT VC or any other format;

After reading the "Credential Format" again, I see it contains both 
- credential format
- signature format
Some specifications define both, but some signature formats are more open.
